/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./index.html",
    "./en/index.html",
    "./assets/js/*.js",
    "./chatbot.js",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#ffffff",
        "on-primary": "#283500",
        "primary-fixed": "#c3f400",
        "primary-fixed-dim": "#abd600",
        "on-primary-fixed": "#161e00",
        "primary-container": "#c3f400",
        "on-primary-container": "#556d00",
        "secondary": "#c6c6c7",
        "on-secondary": "#2f3131",
        "secondary-container": "#454747",
        "on-secondary-container": "#b4b5b5",
        "tertiary": "#ffffff",
        "background": "#131313",
        "on-background": "#e5e2e1",
        "surface": "#131313",
        "surface-dim": "#131313",
        "surface-bright": "#3a3939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "surface-tint": "#abd600",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#c4c9ac",
        "outline": "#8e9379",
        "outline-variant": "#444933",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        "inverse-primary": "#506600",
        "error": "#ffb4ab",
        "error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0px", none: "0px", sm: "0px",
        md: "0px", lg: "0px", xl: "0px",
        "2xl": "0px", "3xl": "0px", full: "0px",
      },
      fontFamily: {
        headline: ["JetBrains Mono", "ui-monospace", "Menlo", "Consolas", "monospace"],
        body: ["Inter", "sans-serif"],
        label: ["JetBrains Mono", "ui-monospace", "Menlo", "Consolas", "monospace"],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
